### ISSUE TITLE
Sample is failing to start

### ISSUE THREAD

**Issue by inuyasha82** [IBM/cloudant-spring#123]
Hello team,

i was trying to build an application using this cloudant boot template, but i can´t get it started. 

I tried both way using an application written from scratch (following example structure) and building this sample, and i always get this error: 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field cloudant in com.ibm.cloud.cloudant.spring.sample.CloudantJavaSdkSpringSampleApplication required a bean of type 'com.ibm.cloud.cloudant.v1.Cloudant' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'com.ibm.cloud.cloudant.v1.Cloudant' in your configuration.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-17.0.12.0.7-2.fc39.x86_64/bin/java'' finished with non-zero exit value 1
```

This output is from just trying to run: 
```
gradle bootRun
``` 

in the samples folder. 
Probably i'm just doing something wrong, can you help me, thanks!

**Comment by ricellis** [comment]
Sorry this is a side effect of being between versions.
If you get the `0.1.5` tagged version of the sample at https://github.com/IBM/cloudant-spring/tree/0.1.5/sample (it should work with Spring `2.7.18`).
`main` migrated the sample deps to Spring boot `3.x` but doesn't yet have a new cloudant-spring release to go with it - that `0.2.0` release will be coming shortly.

**Comment by inuyasha82** [comment]
Thanks @ricellis, do you have an idea of when the new version is going to be released?

**Comment by ricellis** [comment]
Hopefully next week.

**Comment by inuyasha82** [comment]
Perfect, thanks a million, i think i can wait then! :)

**Comment by ricellis** [comment]
Earlier than expected: https://github.com/IBM/cloudant-spring/releases/tag/0.2.0
